### ISSUE TITLE
broken subTapp, Colors, Click behavior by changing to chayns5

### ISSUE THREAD

**Issue by meldau** [TobitSoftware/chayns-js#46]
thx for launching chayns5 that breaks everthing. Another 6h for building workarounds and I can feel that I have not found every bug for now :( We got no color information anymore, navigation click behavior is broken and subtapps (chayns.setSubTapp(config)) are not created anymore - maybe bacause some information are just gone (like tapps sortid) or filled with totaly new content. why the hell???

**Comment by jannikweise** [comment]
Hello @meldau 

We still need some additional information to be able to investigate the problems more closely. So it would be interesting to know exactly where the color information is missing, which config is passed for "setSubTapp", and where the information is filled with new content. Then we can fix the problems. Of course it was not our intention to break something with the release of chayns5, but some changes cannot be avoided.

The sortId for tapps will be added soon. 

By the way, can you please change the title of the issue.

**Comment by meldau** [comment]
Hi Jannik,

in addition to the spoken words I'll give you some more details:
- chayns.setSubTapp() does not create the subTapp anymore. My calls did not change since months and give different options chayns.setSubTapp({tappID,url,name,boldText,color,colorText,sortID,icon,buttonName,isExclusiveView,replaceParent,}). Since sortID is not given anymore withon the env-data I had to put it on zero, although that's not what I need. The subTapp does not appear anymore without logging an error. Calling the tapp anyway with chayns.selectTapp({"id": '._cart_tappID.'}, "comefrom=callingtapp"); promts Tapp not found! /  client.bundle.js:42:63385
- in navigation a click/touch on active page does not fire a new call for the iframe. Ineed to reload the whole page to get actual data send into tapp.
- and yes, the colors. It is neccessary to get a set of used color values to reuse them within css. CSSclassnames are not enough to build a consistent layout. Since users can set their own main color my tapps are unable to give correct layout without getting those values. (the tapp background color e.g. is not even used in one of the given background-classes^^)

**Comment by meldau** [comment]
another one:
the div.cw-wait-cursor lays ontop of the navigation. so the buttons next to the spinner are not clickable anymore.

**Comment by jannikweise** [comment]
Okay, thanks for the information. We will have a look at the problems and try to fix them or find a solution for you.

As soon as I have some news, I'll answer here again.

**Comment by jannikweise** [comment]
We have made some changes.

The chayns call "chayns.setSubTapp()" now also works with the configuration you specified. For information: The value "buttonName" has no effect and the "sortID" is not necessarily needed, because the SubTapp is currently always created below the current tapp, or replaces it if "replaceTapp" is set to "true".

The WaitCursor was adjusted, so that elements next to the WaitCursor are clickable again.

The reloading of tapps by clicking on the current tapp in the navigation is deliberately deactivated in the new version. If the tapp has to be reloaded, this can be solved by "window.location.reload()" within the iFrame.

Regarding the colors, you have already been told elsewhere that there is an adjustment at the CSS server, so that a set of colors for the respective chayns site can be requested there.

I hope we were able to help you so that your tapps work correctly again.

**Comment by meldau** [comment]
hmm, @jannikweise , setting subTapp on fixed position and ignore sortID now is not nice, but I can arrange with it. But you should still use a given tappID to avoid multiple tapps.

If I have 2 or more tapps installed I need the option also to create ONE more navigaion point. Until chayns5 only one tapp for an id was created - as to expect. Now each tapp creates his own subTapp so the user gets multiple tapps with the same name and the same content. (the first called developer tapp should create the subtapp)

thanks for rethinking your changes.
Marcus
